name: Build

on:
  schedule:
    # Every day at 9AM EST
    - cron:  '0 13 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
            docker build --tag deephaven-examples/sentiment-analysis .
            docker-compose up -d
      - name: Run Python script
        uses: ./.github/actions/run-python-script
        with:
          script-paths: ./python-scripts/queries.py
          host: localhost
      - name: Validate tables
        uses: deephaven/action-assert-dh-tables-present@v1
        with:
          table-names: built_in_sia_all,custom_sia_all,built_in_sia_wsb,custom_sia_wsb,built_in_sia_hackernews,custom_sia_hackernews
          host: localhost
